-- MySQL Script generated by MySQL Workbench
-- Tue Sep 27 21:27:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema midigital
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema midigital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `midigital` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `midigital` ;

-- -----------------------------------------------------
-- Table `midigital`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `midigital`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `admin` VARCHAR(45) NOT NULL,
  `general` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `midigital`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `midigital`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `confirmPassword` VARCHAR(45) NOT NULL,
  `role_id` INT NOT NULL,
  `avatar` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `role_id`),
  INDEX `fk_users_category_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_category`
    FOREIGN KEY (`role_id`)
    REFERENCES `midigital`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `midigital`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `midigital`.`type` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `midigital`.`size`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `midigital`.`size` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `midigital`.`fees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `midigital`.`fees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `midigital`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `midigital`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `midigital`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `midigital`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(60) NOT NULL,
  `price` INT NOT NULL,
  `type_id` INT NOT NULL,
  `size_id` INT NOT NULL,
  `fees_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`, `type_id`, `size_id`, `fees_id`, `category_id`),
  INDEX `fk_products_type1_idx` (`type_id` ASC) VISIBLE,
  INDEX `fk_products_size1_idx` (`size_id` ASC) VISIBLE,
  INDEX `fk_products_fees1_idx` (`fees_id` ASC) VISIBLE,
  INDEX `fk_products_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_type1`
    FOREIGN KEY (`type_id`)
    REFERENCES `midigital`.`type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_size1`
    FOREIGN KEY (`size_id`)
    REFERENCES `midigital`.`size` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_fees1`
    FOREIGN KEY (`fees_id`)
    REFERENCES `midigital`.`fees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `midigital`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `midigital`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `midigital`.`image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `products_id` INT NOT NULL,
  PRIMARY KEY (`id`, `products_id`),
  INDEX `fk_image_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_image_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `midigital`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
